
#define IDC_TITLE      10
#define IDC_BACKGROUND 20
#define IDC_CONTENT    30
#define IDC_BTN_OK     40
#define IDC_BTN_CANCEL 50

#define IDC_ROW_GROUP 100
#define IDC_ROW_NAME 101
#define IDC_ROW_CHECKBOX 102
#define IDC_ROW_EDIT 103
#define IDC_ROW_COMBO 104
#define IDC_ROW_TOOLBOX 105
#define IDC_ROW_SIDES_BLUFOR 106
#define IDC_ROW_SIDES_OPFOR 107
#define IDC_ROW_SIDES_INDEPENDENT 108
#define IDC_ROW_SIDES_CIVILIAN 109
#define IDC_ROW_COLOR_PREVIEW 110
#define IDC_ROW_COLOR_RED 111
#define IDC_ROW_COLOR_RED_EDIT 112
#define IDC_ROW_COLOR_GREEN 113
#define IDC_ROW_COLOR_GREEN_EDIT 114
#define IDC_ROW_COLOR_BLUE 115
#define IDC_ROW_COLOR_BLUE_EDIT 116
#define IDC_ROW_COLOR_ALPHA 117
#define IDC_ROW_COLOR_ALPHA_EDIT 118
#define IDC_ROW_SLIDER 119
#define IDC_ROW_SLIDER_EDIT 120
#define IDC_ROW_VECTOR_X 121
#define IDC_ROW_VECTOR_Y 122
#define IDC_ROW_VECTOR_Z 123

#define IDCS_ROW_SIDES [IDC_ROW_SIDES_OPFOR, IDC_ROW_SIDES_BLUFOR, IDC_ROW_SIDES_INDEPENDENT, IDC_ROW_SIDES_CIVILIAN]
#define IDCS_ROW_COLOR [IDC_ROW_COLOR_RED, IDC_ROW_COLOR_GREEN, IDC_ROW_COLOR_BLUE, IDC_ROW_COLOR_ALPHA]
#define IDCS_ROW_COLOR_EDIT [IDC_ROW_COLOR_RED_EDIT, IDC_ROW_COLOR_GREEN_EDIT, IDC_ROW_COLOR_BLUE_EDIT, IDC_ROW_COLOR_ALPHA_EDIT]
#define IDCS_ROW_VECTOR [IDC_ROW_VECTOR_X, IDC_ROW_VECTOR_Y, IDC_ROW_VECTOR_Z]
