
#define IDC_TITLE      10
#define IDC_BACKGROUND 20
#define IDC_CONTENT    30
#define IDC_BTN_OK     40
#define IDC_BTN_CANCEL 50

#define IDC_ROW_GROUP 100
#define IDC_ROW_NAME 101
#define IDC_ROW_CHECKBOX 102
#define IDC_ROW_EDIT 103
#define IDC_ROW_COMBO 104
#define IDC_ROW_TOOLBOX 105
#define IDC_ROW_SIDES_BLUFOR 106
#define IDC_ROW_SIDES_OPFOR 107
#define IDC_ROW_SIDES_INDEPENDENT 108
#define IDC_ROW_SIDES_CIVILIAN 109

#define IDCS_ROW_SIDES [IDC_ROW_SIDES_OPFOR, IDC_ROW_SIDES_BLUFOR, IDC_ROW_SIDES_INDEPENDENT, IDC_ROW_SIDES_CIVILIAN]
