#define COMPONENT editor
#define COMPONENT_BEAUTIFIED Editor
#include "\x\zen\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_EDITOR
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_EDITOR
    #define DEBUG_SETTINGS DEBUG_SETTINGS_EDITOR
#endif

#include "\x\zen\addons\main\script_macros.hpp"

#include "\a3\ui_f\hpp\defineDIKCodes.inc"
#include "\a3\ui_f\hpp\defineCommonGrids.inc"
#include "\x\zen\addons\common\defineResinclDesign.inc"

#include "script_idc.hpp"

#define IDCS_MODE_BUTTONS [ \
    IDC_RSCDISPLAYCURATOR_MODEUNITS, \
    IDC_RSCDISPLAYCURATOR_MODEGROUPS, \
    IDC_RSCDISPLAYCURATOR_MODEMODULES, \
    IDC_RSCDISPLAYCURATOR_MODEMARKERS, \
    IDC_RSCDISPLAYCURATOR_MODERECENT \
]

#define IDCS_SIDE_BUTTONS [ \
    IDC_RSCDISPLAYCURATOR_SIDEOPFOR, \
    IDC_RSCDISPLAYCURATOR_SIDEBLUFOR, \
    IDC_RSCDISPLAYCURATOR_SIDEINDEPENDENT, \
    IDC_RSCDISPLAYCURATOR_SIDECIVILIAN, \
    IDC_RSCDISPLAYCURATOR_SIDEEMPTY \
]

#define IDCS_UNIT_TREES [ \
    IDC_RSCDISPLAYCURATOR_CREATE_UNITS_WEST, \
    IDC_RSCDISPLAYCURATOR_CREATE_UNITS_EAST, \
    IDC_RSCDISPLAYCURATOR_CREATE_UNITS_GUER, \
    IDC_RSCDISPLAYCURATOR_CREATE_UNITS_CIV, \
    IDC_RSCDISPLAYCURATOR_CREATE_UNITS_EMPTY \
]

#define IDCS_GROUP_TREES [ \
    IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_WEST, \
    IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_EAST, \
    IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_GUER, \
    IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_CIV, \
    IDC_RSCDISPLAYCURATOR_CREATE_GROUPS_EMPTY \
]
