PREP(declutterEmptyTree);
PREP(fixSideButtons);
PREP(handleObjectPlaced);
PREP(handleSearchButton);
PREP(handleSearchClick);
PREP(handleSearchKeyDown);
PREP(handleSearchKeyUp);
PREP(handleTreeButtons);
PREP(initDisplayCurator);
