name: Arma

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Validate Return Types
      run: python3 tools/return_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'addons'

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT build
      run: hemtt build
    - name: Rename build folder
      run: mv .hemttout/build .hemttout/@zen
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zen-${{ github.sha }}-nobin
        path: .hemttout/@*
        include-hidden-files: true # Because .hemttout is a hidden directory
        if-no-files-found: error
